
version: '3.8'

services:

  
  db:
    image: mysql:8.0
    container_name: dms_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_DATABASE: evenlister_gki   
    ports:
     
      - "3307:3306"
    volumes:
      
      - db-data:/var/lib/mysql

 
  app:
   
    build: .
    container_name: dms_spring_app
    restart: on-failure
    
    depends_on:
      - db
    ports:
     
      - "8080:8080"
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/evenlister_gki?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 


volumes:
  db-data: